# Generated by Django 3.0.2 on 2020-01-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='size_inches',
            field=models.CharField(choices=[('7 inches ', '7 inches '), ('9 inches ', '9 inches ')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ml',
            field=models.CharField(choices=[('80 ML ', '80 ML '), ('100 ML ', '100 ML '), ('130 ML ', '130 ML '), ('150 ML ', '150 ML '), ('200 ML ', '200 ML '), ('225 ML ', '225 ML '), ('250 ML ', '250 ML '), ('350 ML ', '350 ML ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hot & Cold Cup', 'Hot & Cold Cup'), ('Ice Cream Cup', 'Ice Cream Cup'), ('Bowl', 'Bowl'), ('Plate & Tray', 'Plate & Tray'), ('Muffin Cup', 'Muffin Cup'), ('Cup with Lid Jacket', 'Cup with Lid Jacket'), ('Food Box', 'Food Box'), ('Cup with Handle', 'Cup with Handle')], max_length=30, null=True),
        ),
    ]
