# Generated by Django 3.0.2 on 2020-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200112_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_inches',
            field=models.CharField(choices=[('', ''), ('7 inches ', '7 inches '), ('9 inches ', '9 inches ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_ml',
            field=models.CharField(choices=[(' ', ' '), ('80 ML ', '80 ML '), ('100 ML ', '100 ML '), ('130 ML ', '130 ML '), ('150 ML ', '150 ML '), ('200 ML ', '200 ML '), ('225 ML ', '225 ML '), ('250 ML ', '250 ML '), ('350 ML ', '350 ML ')], max_length=10, null=True),
        ),
    ]
