# Generated by Django 3.0.2 on 2020-01-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=5, null=True)),
                ('transaction_type', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('customer_id', models.CharField(max_length=6, null=True)),
                ('customer_name', models.CharField(max_length=30, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
