# Generated by Django 3.0.2 on 2020-01-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=10, null=True),
        ),
    ]
