# Generated by Django 3.0.2 on 2020-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200117_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
    ]
